### ISSUE TITLE
Message cancellation

### ISSUE THREAD

**Issue by qsantos** [robalb/morsechat#1]
I know you are working on it, but it feels nice to close feature requests ;-) .

As a beginner in Morse keying, I often make mistakes when writing a message, and I would often rather stratch back from scratch when there are so many errors that the message is undecipherable. Simply having to hit `Escape` would be nice!

**Comment by robalb** [comment]
damn right, thanks for the feedback

**Comment by Rexogamer** [comment]
also: if this was added, it would be great to have a way to do so on mobile (eg a delete button next to the message bar or something)

**Comment by robalb** [comment]
Lol this took some years, but i can finally close this request. The feature has been added to the new version of the website
