### ISSUE TITLE
Keying table truncated

### ISSUE THREAD

**Issue by qsantos** [robalb/morsechat#2]
Depending on the resolution, font size, and zoom level, the rightmost part of the keying table is not always visible (see on screenshot below). For instance, in my default setting, I see `!` and `;` both as `-.-.-` rather than `-.-.--` and `-.-.-.` respectively. Adding a bit of padding should do.

![screenshot-2018-5-14 morse chat](https://user-images.githubusercontent.com/8493765/40019178-c33c123e-57be-11e8-84c4-40891649eeed.png)

**Comment by robalb** [comment]
this should be fixed now
