### ISSUE TITLE
XSS in makepassword.php

### ISSUE THREAD

**Issue by ebelties** [robalb/morsechat#3]
Hey,

The `makepassword.php` file is vulnerable for Cross-Site Scripting (XSS).

**Here a working example:**
http://www.halb.it/morsecode/app/makepassword.php?password=%3Cscript%3Ealert(document.cookie);%3C/script%3E  

To fix:
```php
/*  bad */ $_GET["password"]
/* good */ htmlentities( $_GET["password"], ENT_QUOTES, "UTF-8" )
```
Not really a big impact, but would be good to fix. Also good to keep in mind for other projects.

Cheers!

**Comment by robalb** [comment]
Thanks, when i created this page i didn't planned it as something to use in production, so i simply ignored any security aspect. I think i'll delete it completely since it's not very useful, and bcrypt hashes can be easily generated from other sources.
