### ISSUE TITLE
Messages won't broadcast

### ISSUE THREAD

**Issue by ChillNSD** [robalb/morsechat#4]
I love your program and have been trying to use it. However, after I upload all of my code and connect my PUSHER.com account my message preview works, but the message doesn't actually broadcast.

Here is my website if you want to look.
http://morsepractice.epizy.com/?ch=1

**Comment by robalb** [comment]
Sorry, i wrote this code a long time ago, and i didn't follow proper code practices. It is probably an issue related to wrong import paths or something like that. Anyway in these days i'm migrating the website to a new server (it's offline now for this reason) so i'll find a way to improve the whole installation process as much as possible. I'm trying to find the time to add webpack for all the loose js files, and probably docker
