### ISSUE TITLE
settings modal freezes

### ISSUE THREAD

**Issue by AnIntellectualFella** [robalb/morsechat#5]
When I try to import my configuration code it wont let me get out of settings, ples fix soon I really love the program.

**Comment by robalb** [comment]
Thanks for the feedback. That's an odd bug, could you give me more info? 
Specifically, what browser and device are you using?
Also, you can't leave  because there is no x button, or because when you click it nothing happens?

**Comment by robalb** [comment]
closed because i couldn't reproduce it
