### ISSUE TITLE
Site not working

### ISSUE THREAD

**Issue by OliveOil77** [robalb/morsechat#9]
"This site can’t be reached" not only on my PC or in my region but worldwide.

**Comment by robalb** [comment]
Hi!
the website was hosted on OVH, in the infamous datacenter that took the concept of cloud hosting [too literally](https://www.reuters.com/article/us-france-ovh-fire-idUSKBN2B20NU) last week.
I was waiting for some news from OVH, but i suspect that the only thing i can do is buy and set up a new vps. With some luck everything will be back to normal in a couple of days

**Comment by robalb** [comment]
closing this since the website is now fully functional again
